/**
 * Vendors the built site-kit into this repo.
 *
 * site-kit is the single source of truth and lives in a sibling directory, but
 * Vercel uploads only the project directory, so a `file:../site-kit` dependency
 * cannot resolve at deploy time. This copies the built output in and commits it.
 *
 * The canonical package is still ../site-kit. Edit there, then run this.
 *
 *   npm run sync:kit
 */
import { cp, rm, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const SRC = path.resolve(process.cwd(), "..", "site-kit");
const DEST = path.resolve(process.cwd(), "packages", "site-kit");

if (!existsSync(path.join(SRC, "dist"))) {
  console.error(`No build at ${SRC}/dist. Run "npm run build" in site-kit first.`);
  process.exit(1);
}

await rm(DEST, { recursive: true, force: true });
await mkdir(DEST, { recursive: true });
await cp(path.join(SRC, "dist"), path.join(DEST, "dist"), { recursive: true });

// Ship dist only: no source, no build scripts, no devDependencies.
const pkg = JSON.parse(await readFile(path.join(SRC, "package.json"), "utf8"));
const vendored = {
  name: pkg.name,
  version: pkg.version,
  type: pkg.type,
  private: true,
  description: `${pkg.description} Vendored copy, generated by scripts/sync-kit.mjs. Do not edit.`,
  main: pkg.main,
  types: pkg.types,
  exports: pkg.exports,
  dependencies: pkg.dependencies,
};
await writeFile(path.join(DEST, "package.json"), JSON.stringify(vendored, null, 2) + "\n");
await writeFile(
  path.join(DEST, "README.md"),
  "# Vendored\n\nGenerated from `../../site-kit` by `npm run sync:kit`. Do not edit here.\n",
);

console.log(`Vendored ${pkg.name}@${pkg.version} into packages/site-kit`);
